### PR TITLE
Issue 116 ✨ feature allow searching for assets in all asset id fields

### LINKED ISSUE #116: ✨ Feature: Allow searching for assets in all asset id fields
# ℹ Overview

Allow searching for Asset Id or Asset Name similar to how Algo Explorer does it. Then put the full name with the asset id into the asset id field. The underlying value should be the number itself.

image

Use the Algoexplorer API: https://indexer.algoexplorerapi.io/rl/v1/search?keywords=frog

### PR DESCRIPTION
**Pull request by treasurechic**
# ℹ Overview

### 📝 Related Issues

closes #116

### CODE REVIEW

**Review by atrefonas — CHANGES_REQUESTED** [review]
I am unable to type anything into the box


https://user-images.githubusercontent.com/72869083/169308174-9d8b4583-0617-4734-8671-d23a9e540e73.mp4


x

**Comment by treasurechic** [comment]
> I am unable to type anything into the box
> 
>  ice_video_20220519-094229_edit_0.1.mp4 
> x

You need to connect your wallet

**Comment by treasurechic** [comment]
I think I should remove that for the text box.
Users should be able to type in the assetid even if the wallet is not connected.....What do you think?

**Comment by atrefonas** [comment]
> I think I should remove that for the text box. Users should be able to type in the assetid even if the wallet is not connected.....What do you think?

yes, you should be able to type it in even before your wallet is connected

**Pull request merged**
