### PR TITLE
:bug: :construction: Redirect proxy server to prevent CORS

### LINKED ISSUE #213: 🐛 Fix: CORS error on transaction history endpoint
# ℹ Overview

### 💻 System Configuration

- Operating System:
    - Edition: 
    - Version: 
    - Build: 
- Browser:
    - Type: 
    - Version:

### PR DESCRIPTION
**Pull request by treasurechic**
# ℹ Overview

### 📝 Related Issues

closes #213

### CODE REVIEW

**Comment by PhearZero** [comment]
This is being blocked by the provider(PureStake), the only solution currently is to launch our own indexer with the notes prefix enabled.

It's failing on CORs because of the 400 error has CORs enabled making it misleading. The other endpoints are valid and allow public access
```
Error: Network request error. Received status 400: provided disabled parameter: note-prefix
```

**Comment by treasurechic** [comment]
> This is being blocked by the provider(PureStake), the only solution currently is to launch our own indexer with the notes prefix enabled.
> 
> It's failing on CORs because of the 400 error has CORs enabled making it misleading. The other endpoints are valid and allow public access
> 
> ```
> Error: Network request error. Received status 400: provided disabled parameter: note-prefix
> ```

@PhearZero How about the frontend makes a call to our backend and our backend makes the call to the purestake directly on the back and return the response to the frontend?.....I think the CORs might be prevented that way.

**Comment by PhearZero** [comment]
> How about the frontend makes a call to our backend and our backend makes the call to the purestake directly on the back and return the response to the frontend?.....I think the CORs might be prevented that way.

@treasurechic The notes field search is disabled from PureStake, there is nothing we can do right now to resolve it. We would need to launch our own Algorand Indexer to support the notes field.

**Comment by treasurechic** [comment]
> > How about the frontend makes a call to our backend and our backend makes the call to the purestake directly on the back and return the response to the frontend?.....I think the CORs might be prevented that way.
> 
> @treasurechic The notes field search is disabled from PureStake, there is nothing we can do right now to resolve it. We would need to launch our own Algorand Indexer to support the notes field.

Ohh....I understand that now

**Pull request closed without merging**
