### PR TITLE
:zap: Pop-up blocker warning

### PR DESCRIPTION
**Pull request by treasurechic**
# ℹ Overview

### CODE REVIEW

**Review by atrefonas — CHANGES_REQUESTED** [review]
I am not seeing a message for the popup blocker

image


Please look at how the algodex-react project handles it.

**Review by atrefonas — CHANGES_REQUESTED** [review]
Works for me now. However, can you check for "PopupOpenError" as well? As there are different browsers.

This is how algodex-react does it:
```

 if (/PopupOpenError|blocked/.test(err)) {
          return detectMobileDisplay() ? t('disable-popup-mobile') : t('disable-popup')
        }
```

**Review by atrefonas — CHANGES_REQUESTED** [review]
Can we make the message a bit wider?

image

**Comment by treasurechic** [comment]
@atrefonas  Can I do this in another PR so I can merge this, making this change will conflict with some other issues  have treated in the new branches I created

**Pull request merged**
