### PR TITLE
Issue 100 ✨ feature replace the text area in send history with a scrollable standard table component

### PR DESCRIPTION
**Pull request by treasurechic**
# ℹ Overview

### CODE REVIEW

**Review by atrefonas — CHANGES_REQUESTED** [review]
On desktop, the table should auto-expand to fill the page horizontally

image

**Review by atrefonas — CHANGES_REQUESTED** [review]
Looks better. Is it possible to hide the scrollbar when the full width is visible? overflow: auto or something?

image

**Review by atrefonas — CHANGES_REQUESTED** [review]
It's not looking good on mobile:

image


Also on desktop, can you make the table have a larger height so it shows about 6 rows max?

**Review by atrefonas — CHANGES_REQUESTED** [review]
It says 1-3 of 3 but there are only 2 rows:

68867813
WYWRYK42XADLY3O62N52BOLT27DMPRA3WNBT2OBRT65N6OEZQWD4OSH6PI

image

**Comment by treasurechic** [comment]
> It says 1-3 of 3 but there are only 2 rows:
> 
> 68867813 WYWRYK42XADLY3O62N52BOLT27DMPRA3WNBT2OBRT65N6OEZQWD4OSH6PI
> 
> image

Ohhh.....I know why.

Will fix now

**Review by atrefonas — APPROVED** [review]
Looks great!

**Pull request merged**
