### PR TITLE
✨ Converts to MUI baseline

### LINKED ISSUE #6: ♻ Refactor: Convert Layout to MUI
# ℹ Overview

Refactor Layout to use MUI Layout components. Remove `layout.css.js`. Fix `theme.js` to be a standard theme. Remove `styled-components` and `grommet`

### ♻ `<Header>` -> `<Toolbar>`

header.js should be refactored to use `<Toolbar>` and passed into `<Layout>` in `__app.js` (See Layout Bellow)

### 🚚 `<NavBarItem>` -> `<Link>` && `<ListItemLink>`

`nav-bar-item.js` should be renamed to be called "Link.js" and rename it's constant to "Link"
Create a new `<ListItemLink>` to be used in the `<Drawer>`

```jsx
import NextLink from 'next/link'
import {ListItem, ListItemIcon, ListItemText} from '@mui/material'
import PropTypes from 'prop-types'
import {forwardRef, useMemo} from 'react'

function ListItemLink(props) {
  const { icon, primary, to} = props;
  const router = useRouter()
  const activeNav = router.asPath
  
  const renderLink = useMemo(
    () =>
      forwardRef(function Link(itemProps, ref) {
        return <NextLink to={to} ref={ref} {...itemProps} role={undefined} />;
      }),
    [to],
  );

  return (
    <li>
      <ListItem button selected={activeNav === to} component={renderLink}>
        {icon ? <ListItemIcon>{icon}</ListItemIcon> : null}
        <ListItemText primary={primary} />
      </ListItem>
    </li>
  );
}

ListItemLink.propTypes = {
  icon: PropTypes.element,
  primary: PropTypes.string.isRequired,
  to: PropTypes.string.isRequired,
};

```

### ♻`<NavBar>`  -> `<Drawer>`

nav-bar.js should be refactored to a `<Drawer>` that has a `<List>` of `<ListItem>` that are a `<Link>`.
The `<ListItem>` can use the router to select which one is "Active".
```jsx
const Drawer = (props) => {
  return (
  <MUIDrawer {...props}>
      <List>
         <ListItemLink  to="/" primary="Homepage"/>
      </List>
   </MUIDrawer>
  )
}
```

### ✨`<Layout> + <MainBody>` -> MUI + Slots

Layout should have `components` slots  for `<Toolbar>`, `<BottomNavigation>` and `<Drawer>`. 

```jsx
export function Layout({children, components, componentsProps}){
  const {Toolbar, BottomNavigation, Drawer} = components
  return (
    <>
      <AppBar position="fixed" sx={{ zIndex: (theme) => theme.zIndex.drawer + 1 }}>
        <Toolbar {...componentsProps.Toolbar}/>
      </AppBar>
      <Drawer {...componentsProps.Drawer} />
      <Container>
        <Toolbar/>
        {children}
      </Container>
      <Paper sx={{ position: 'sticky', bottom: 0, left: 0, right: 0 }} elevation={3}>
        <BottomNavigation {...componentsProps.BottomNavigation}/>
      </Paper>
    </>
  )
}

Layout.defaultProps = {
  components: {
    Toolbar: DefaultToolbar,
    BottomNavigation: DefaultBottomNavigation,
    Drawer: DefaultDrawer
  },
  componentsProps: {
    Toolbar: {},
    BottomNavigation: {},
    Drawer: {}
  }
}
```

### ⚙ `<App>` -> Use Layout

Use the Layout in the `./pages/_app.js` and pass the component render as a child to `<Layout>`

```jsx
import Drawer from 'components/Drawer'
import Toolbar from 'components/Toolbar'
import BottomNavigation from 'components/BottomNavigation'

export default function App(props) {
  const { Component, emotionCache = clientSideEmotionCache, pageProps } = props;

  return (
    <CacheProvider value={emotionCache}>
      <Head>
        <title>Algodex Mailbox</title>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <ThemeProvider theme={theme}>
        {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
        <CssBaseline />
        <Layout components={{Drawer, Toolbar, BottomNavigation}}>
           <Component {...pageProps} />
        </Layout>
      </ThemeProvider>
    </CacheProvider>
  );
}
```

### 🎨 Pages

Remove `<Layout>` from pages, it will be provided by `_app`. Just return the "Content" and it will become the `children` of `<Layout>` in `_app.js`

### PR DESCRIPTION
**Pull request by PhearZero**
# ℹ Overview

Sets good baseline for project with `<Nav>` components. Nav components are dependent on `next/router` and loaded as an "Application Shell" for performance and optimization reasons.

### CODE REVIEW

**Review by atrefonas — CHANGES_REQUESTED** [review]
Overall it's a good refactor - styling wise can you please make the pink a more faded color, or else switch to gray? It is much too bright. Maybe switch to this blue-ish hue? #C9C9E7

Also can you fix the Vercel build issues (I guess from the linter)? https://vercel.com/algodex-dev/algodex-mailbox/5obiqrGJmGTVKR7mw8iQCH2LPPzY

**Comment by PhearZero** [comment]
>  It is much too bright. Maybe switch to this blue-ish hue?

My style is flawless 🕺 💄! Check out the color picker and I'll update the theme:

https://mui.com/customization/color/

Live editor:
https://material.io/resources/color

**Comment by atrefonas** [comment]
Can you make it indigo 100 for MUI, i.e. #c5cae9, which is close to the one I mentioned?

Steph agreed with me about the first color I picked.

**Comment by PhearZero** [comment]
> Can you make it indigo 100 for MUI, i.e. #c5cae9, which is close to the one I mentioned?

Yea sure thing, I pushed some complimentary primary/secondary colors based on  #C9C9E7. I can do the same for Indigo 100 or you can pick a decent baseline for secondary.

Color wheel is useful to picking the 2nd color(at least until it gets a formal design review)
https://www.canva.com/colors/color-wheel/

**Review by atrefonas — APPROVED** [review]
Looks fine for now

**Pull request merged**
